const vehicleConfig = [
  {
    id: 'city-car',
    type: 'car',
    domain: 'ground',
    name: 'City Car',
    modelPath: '/model/vehicles/car.glb',
    speed: 0.055,
    color: '#3ddad7',
    size: [1.4, 0.6, 0.9],
    spawnCondition: { phases: ['pagi', 'siang', 'sore', 'malam'], weather: ['cerah', 'hujan'] },
  },
  {
    id: 'metro-taxi',
    type: 'taxi',
    domain: 'ground',
    name: 'Metro Taxi',
    modelPath: '/model/vehicles/taxi.glb',
    speed: 0.06,
    color: '#ffd166',
    size: [1.45, 0.6, 0.9],
    spawnCondition: { phases: ['pagi', 'siang', 'sore', 'malam'], weather: ['cerah', 'hujan'] },
  },
  {
    id: 'commuter-bus',
    type: 'bus',
    domain: 'ground',
    name: 'Commuter Bus',
    modelPath: '/model/vehicles/bus.glb',
    speed: 0.042,
    color: '#ef476f',
    size: [2.5, 0.9, 1.1],
    spawnCondition: { phases: ['pagi', 'siang', 'sore'], weather: ['cerah', 'hujan'] },
  },
  {
    id: 'cargo-truck',
    type: 'truck',
    domain: 'ground',
    name: 'Cargo Truck',
    modelPath: '/model/vehicles/truck.glb',
    speed: 0.046,
    color: '#8d99ae',
    size: [2.1, 0.9, 1],
    spawnCondition: { phases: ['pagi', 'siang', 'sore', 'malam'], weather: ['cerah', 'hujan'] },
  },
  {
    id: 'island-ship',
    type: 'ship',
    domain: 'water',
    name: 'Island Ship',
    modelPath: '/model/vehicles/ship.glb',
    speed: 0.02,
    color: '#4d96ff',
    size: [3, 0.8, 1.2],
    spawnCondition: { phases: ['pagi', 'siang', 'sore', 'malam'], weather: ['cerah', 'hujan'] },
  },
  {
    id: 'airport-plane',
    type: 'plane',
    domain: 'air',
    name: 'Airport Plane',
    modelPath: '/model/vehicles/plane.glb',
    speed: 0.032,
    color: '#f8f9fa',
    size: [3.6, 0.5, 1.5],
    spawnCondition: { phases: ['pagi', 'siang', 'sore'], weather: ['cerah'] },
  },
];

export default vehicleConfig;
