import * as THREE from 'three';
export function createAudioSystem(settings, getDayNight) {
  let ctx = null, masterGain = null, sfxGain = null, musicPlaying = false, currentMusic = null;
  const menuMusic = new window.Audio('music/main-menu.mp3'); menuMusic.loop = true; menuMusic.volume = 0.35;
  const gameplayMusic = new window.Audio('music/gameplay.mp3'); gameplayMusic.loop = true; gameplayMusic.volume = 0.2;
  const sfxTracks = { morning:new window.Audio('music/sfx/morning.mp3'), evening:new window.Audio('music/sfx/evening.mp3'), night:new window.Audio('music/sfx/night.mp3'), rain:new window.Audio('music/sfx/rain.mp3') };
  Object.values(sfxTracks).forEach(track => { track.loop = true; track.volume = 0; });
  let currentSfxKey = null;
  const ensureCtx = () => { if (!ctx) { ctx = new (window.AudioContext || window.webkitAudioContext)(); masterGain = ctx.createGain(); sfxGain = ctx.createGain(); masterGain.gain.value = 0.6; sfxGain.gain.value = 0.7; sfxGain.connect(masterGain); masterGain.connect(ctx.destination); } return ctx; };
  const osc = (freq, type, dur, gainVal) => { const c = ensureCtx(); const o = c.createOscillator(); const g = c.createGain(); o.type = type; o.frequency.value = freq; g.gain.setValueAtTime(gainVal, c.currentTime); g.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + dur); o.connect(g); g.connect(sfxGain); o.start(); o.stop(c.currentTime + dur + 0.05); };
  const desiredSfx = () => { const dn = getDayNight(); if (!dn) return null; if (dn.weather === 'rain') return 'rain'; if (dn.isNight) return 'night'; return dn.dayT < 0.43 ? 'morning' : 'evening'; };
  const tickSfxAmbience = () => { const desired = desiredSfx(); if (!settings.sound) { Object.values(sfxTracks).forEach(t => { t.volume = 0; }); currentSfxKey = null; return; } if (desired === currentSfxKey) return; currentSfxKey = desired; Object.entries(sfxTracks).forEach(([key, track]) => { if (key === desired) { track.volume = key === 'rain' ? 0.55 : 0.35; track.play().catch(() => {}); } else { track.pause(); track.currentTime = 0; track.volume = 0; } }); };
  return { init:() => { menuMusic.play().catch(() => {}); musicPlaying = true; tickSfxAmbience(); }, playMenuMusic:() => { gameplayMusic.pause(); gameplayMusic.currentTime = 0; menuMusic.play().catch(() => {}); currentMusic = menuMusic; musicPlaying = true; }, playGameplayMusic:() => { menuMusic.pause(); menuMusic.currentTime = 0; gameplayMusic.play().catch(() => {}); currentMusic = gameplayMusic; musicPlaying = true; setTimeout(tickSfxAmbience, 1000); }, stopAllMusic:() => { menuMusic.pause(); gameplayMusic.pause(); menuMusic.currentTime = 0; gameplayMusic.currentTime = 0; currentMusic = null; musicPlaying = false; }, stopAllSfxAmbience:() => { Object.values(sfxTracks).forEach(track => { track.pause(); track.currentTime = 0; track.volume = 0; }); currentSfxKey = null; }, stopAllMusicAndSfx:() => { menuMusic.pause(); gameplayMusic.pause(); Object.values(sfxTracks).forEach(track => { track.pause(); track.currentTime = 0; track.volume = 0; }); }, playPlace:() => { ensureCtx(); osc(520, 'sine', 0.08, 0.4); }, playBulldoze:() => { ensureCtx(); osc(80, 'sawtooth', 0.2, 0.3); }, playError:() => { ensureCtx(); osc(220, 'square', 0.1, 0.3); }, playNotify:(type='info') => { ensureCtx(); if (type === 'danger') osc(440, 'square', 0.08, 0.3); else if (type === 'success') osc(523, 'sine', 0.07, 0.25); else osc(660, 'sine', 0.06, 0.2); }, playClick:() => { ensureCtx(); osc(880, 'sine', 0.03, 0.1); }, playLevelUp:() => { ensureCtx(); [523,659,784,1047].forEach((freq, index) => setTimeout(() => osc(freq, 'sine', 0.12, 0.25), index * 90)); }, playRotate:() => { ensureCtx(); osc(880, 'sine', 0.05, 0.15); }, setEnabled:on => { settings.sound = on; if (!on && masterGain) masterGain.gain.value = 0; else if (masterGain) masterGain.gain.value = 0.6; tickSfxAmbience(); }, setMusicVol:v => { if (currentMusic) currentMusic.volume = v; }, setSfxVol:v => { ensureCtx(); sfxGain.gain.value = v; }, setMasterVol:v => { ensureCtx(); masterGain.gain.value = v; }, tickSfxAmbience };
}
export { THREE };
